# Step 1: use an official maven image to build the app with Java 25
FROM eclipse-temurin:25-jdk as build

# Install Maven
RUN apt-get update && apt-get install -y maven && rm -rf /var/lib/apt/lists/*

# Step 2: set the working directory inside the container
WORKDIR /app

# Step 3: copy the pom.xml and source code to the working directory
COPY pom.xml .
COPY src ./src

# Step 4: build the application
RUN mvn clean package -DskipTests

FROM eclipse-temurin:25-jre

# Step 5: set the working directory inside the container
WORKDIR /app

# Step 6: copy the built jar file from the build stage
COPY --from=build /app/target/*.jar app.jar

# Step 7: expose the application port
EXPOSE 8080

# Step 8: define the command to run the application
ENTRYPOINT ["java", "-jar", "app.jar"]


# docker build -t docker-container:latest .
# docker run -p 8080:8080 docker-container:latest