spring:
  application:
    name: API-Gateway
  config:
    import: "optional:configserver:http://localhost:9000"
  cloud:
    gateway:
      routes:
        - id: AUTH-JWT-SERVICE
          uri: lb://AUTH-JWT-SERVICE
          predicates:
            - Path=/api/auth/**
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
          filters:
            - AuthenticationFilter
        - id: CATEGORY-SERVICE
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/api/categories/**
          filters:
            - AuthenticationFilter
